components_manager:
    task_processors:

        main-task-processor:
            worker_threads: $worker-threads       

        fs-task-processor:
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:          
        server:
            listener:     
                port: $server-port  
                task_processor: main-task-processor  
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard 

        dynamic-config:
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        http-client:
            fs-task-processor: fs-task-processor
        resources-cache:
            dir: /home/segoon/projects/upastebin/www-data
            update-period: 1s
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-store:
            path: /api/v1/posts
            method: POST
            task_processor: main-task-processor
        handler-latest:
            path: /api/v1/latest
            method: GET
            task_processor: main-task-processor
        handler-retrieve:
            path: /api/v1/posts/{uuid}
            method: GET
            task_processor: main-task-processor

        handler-redirect:
            path: /
            method: GET
            task_processor: main-task-processor
        handler-text:
            path: /{id}
            method: GET
            task_processor: main-task-processor
        handler-resources:
            path: /r/{subpath}
            method: GET
            task_processor: main-task-processor

        postgres:
            dbconnection: $dbconnection
            dbconnection#env: DB_CONNECTION
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: false
            connlimit_mode: manual

        dns-client:
            fs-task-processor: fs-task-processor
